name: Test OpenSSL

on:
  push:

jobs:
  macOS-11-build:
    runs-on: macos-11
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.9"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python      
        run: brew install python@3.10
        
      - name: Install dependencies and build pyinstaller bundle
        run: | 
          pip install pikepdf pyinstaller
          pyinstaller --onefile --copy-metadata pikepdf tests/test_encryption.py
      
      - name: Upload binary bundle
        uses: actions/upload-artifact@v3
        with:
          name: test_encryption
          path: dist/test_encryption
  
  macOS-12-13-test:
    runs-on: ${{ matrix.os }}
    needs: macOS-11-build
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-12, macos-13]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Download binary bundle
        uses: actions/download-artifact@v3
        with:
          name: test_encryption
      
      - name: Run encryption test
        run: chmod +x test_encryption && ./test_encryption tests/encryption_test.pdf
